# Generated by Django 5.0.6 on 2024-06-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detected_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images'),
        ),
    ]
